[project]
site_name = "DECADE-X Standards"
site_url = "https://shibukawa310.github.io/dx_standards/"

# La liste stricte pour forcer l'affichage du menu à gauche
nav = [
    { "Home" = "index.md" },
    { "Active Standards" = [
        { "DX-0001 Pattern" = "active/AX-001.md" },
        { "DX-0002 Standard" = "active/AX-002.md" },
        { "DX-0003 Standard" = "active/AX-003.md" }
    ]},
    { "Retired Standards" = [
        { "Archives" = "retired/index.md" }
    ]}
]

[project.theme]
name = "material"
# On s'assure qu'il n'y a PAS "navigation.tabs" ici
features = [
    "navigation.sections",
    "search.suggest",
    "search.highlight"
]

[project.markdown_extensions]
attr_list = {}
md_in_html = {}
abbr = {}
admonition = {}

[project.markdown_extensions.pymdownx.snippets]
base_path = "includes"

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
